# ElPatcher AI Agent Workflow
# AI code review for Pull Requests

name: ElPatcher AI Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

env:
  ELPATCHER_API_URL: https://bee30e3a87e5.ngrok-free.app

concurrency:
  group: elpatcher-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  elpatcher-review:
    name: AI Code Review
    runs-on: ubuntu-latest

    if: |
      (
        contains(github.event.pull_request.labels.*.name, 'elpatcher') ||
        contains(github.event.pull_request.labels.*.name, 'ai-review') ||
        startsWith(github.event.pull_request.head.ref, 'elpatcher/')
      ) &&
      github.event.pull_request.head.ref != 'elpatcher/onboarding'

    steps:
      - name: Get AI Review
        id: review
        run: |
          echo "🤖 Requesting AI review for PR #${{ github.event.pull_request.number }}"

          response=$(curl -s -X POST "${{ env.ELPATCHER_API_URL }}/api/review" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Token: ${{ secrets.GITHUB_TOKEN }}" \
            -d '{
              "pr_number": ${{ github.event.pull_request.number }},
              "repo": "${{ github.repository }}",
              "head_sha": "${{ github.event.pull_request.head.sha }}"
            }')

          # Check for errors
          status=$(echo "$response" | jq -r '.status // "error"')
          if [ "$status" != "success" ]; then
            echo "❌ Review API error:"
            echo "$response" | jq .
            exit 1
          fi

          # Extract review data
          approved=$(echo "$response" | jq -r '.approved')
          echo "$response" | jq -r '.review_body' > /tmp/review_body.md

          echo "approved=$approved" >> $GITHUB_OUTPUT

          # Log summary
          echo ""
          echo "📊 Review Summary:"
          echo "$response" | jq -r '.summary'

      - name: Post Review Comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "📝 Posting review comment"
          gh pr comment ${{ github.event.pull_request.number }} \
            --repo ${{ github.repository }} \
            --body-file /tmp/review_body.md

      - name: Check Result
        run: |
          if [ "${{ steps.review.outputs.approved }}" == "true" ]; then
            echo "✅ AI Review: Approved"
            exit 0
          else
            echo "❌ AI Review: Changes Requested"
            exit 1
          fi
